name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  HUSKY: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          # We want to ensure that the Node.js version running here respects our supported versions
          node-version-file: ".nvmrc"
          cache: "pnpm"
      - name: Print versions
        run: |
          git --version
          echo "node version: $(node --version)"
          echo "pnpm version: $(pnpm --version)"
          lsb_release -a
      - name: Install dependencies
        run: pnpm install
      - name: Prettier check
        run: pnpm run fmt.check
      - name: Lint check
        run: pnpm run lint --filter=[origin/main]
      - name: Lint css check
        run: pnpm run lint:css --filter=[origin/main]
      - name: Unit tests and coverage
        run: pnpm run coverage --filter=[origin/main]
      - name: build check
        run: pnpm run build --filter=[origin/main]
